name: test

on: pull_request

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Differential Fuzz Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build-solidity

      - name: Build go test harness
        run: |
          go build -o harness ./fuzz/harness.go
        id: build-go

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
